<?php
/**
 * Plugin Name: Hea-lth Operations
 * Plugin URI: https://hea-lth.co.il
 * Description: Governed operational layer for Hea-lth health checks, release metadata, and future portal services.
 * Version: 0.2.0
 * Requires at least: 6.9
 * Requires PHP: 7.4
 * Author: Hea-lth
 * Text Domain: hea-lth-ops
 *
 * @package HeaLthOps
 */

declare(strict_types=1);

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

const HEA_LTH_OPS_VERSION = '0.2.0';
/**
 * Persist non-secret deployment metadata for independent release verification.
 *
 * @param string $deployment_id Deployment identifier generated by the release pipeline.
 */
function hea_lth_ops_store_deployment( string $deployment_id ): void {

	$deployment_id = sanitize_text_field( $deployment_id );
	if ( '' === $deployment_id || 1 !== preg_match( '/^[a-zA-Z0-9._-]{8,128}$/', $deployment_id ) ) {
		return;
	}

	update_option(
		'hea_lth_ops_last_deployment',
		array(
			'deployment_id' => $deployment_id,
			'version'       => HEA_LTH_OPS_VERSION,
			'deployed_at'   => gmdate( 'c' ),
		),
		false
	);
}

/**
 * Record an authenticated agent deployment without persisting credentials.
 */
function hea_lth_ops_record_deployment(): void {

	$deployment_id = isset( $_SERVER['HTTP_X_HEA_LTH_DEPLOYMENT_ID'] )
	? sanitize_text_field( wp_unslash( (string) $_SERVER['HTTP_X_HEA_LTH_DEPLOYMENT_ID'] ) )
		: '';

	hea_lth_ops_store_deployment(
		$deployment_id
	);
}
register_activation_hook( __FILE__, 'hea_lth_ops_record_deployment' );
/**
 * Register private lead storage for governed intake.
 */
function hea_lth_ops_register_lead_post_type(): void {

	register_post_type(
		'hea_lth_lead',
		array(
			'labels'              => array(
				'name'          => __( 'Hea-lth Leads', 'hea-lth-ops' ),
				'singular_name' => __( 'Hea-lth Lead', 'hea-lth-ops' ),
				'menu_name'     => __( 'Hea-lth Leads', 'hea-lth-ops' ),
			),
			'public'              => false,
			'show_ui'             => true,
			'show_in_menu'        => true,
			'show_in_rest'        => false,
			'exclude_from_search' => true,
			'capability_type'     => 'post',
			'map_meta_cap'        => true,
			'supports'            => array( 'title', 'custom-fields' ),
			'menu_icon'           => 'dashicons-heart',
		)
	);
}
add_action( 'init', 'hea_lth_ops_register_lead_post_type' );
/**
 * Return allow-listed lead service routes.
 *
 * @return array<string,string>
 */
function hea_lth_ops_allowed_services(): array {

	return array(
		'aesthetic-medicine'     => __( 'רפואה אסתטית', 'hea-lth-ops' ),
		'plastic-surgery'        => __( 'כירורגיה פלסטית', 'hea-lth-ops' ),
		'hair-transplant'        => __( 'השתלות שיער ונשירת שיער', 'hea-lth-ops' ),
		'private-medicine'       => __( 'רפואה פרטית', 'hea-lth-ops' ),
		'diagnostics-wellness'   => __( 'בדיקות, אבחון ו-Wellness', 'hea-lth-ops' ),
		'professional-join'      => __( 'הצטרפות מקצוענים', 'hea-lth-ops' ),
		'general-private-health' => __( 'בריאות פרטית כללי', 'hea-lth-ops' ),
	);
}

/**
 * Return a bounded text field from a REST request.
 *
 * @param WP_REST_Request $request REST request.
 * @param string          $key     Field key.
 * @param int             $limit   Character limit.
 * @return string
 */
function hea_lth_ops_request_text( WP_REST_Request $request, string $key, int $limit = 180 ): string {

	$value = $request->get_param( $key );
	if ( is_array( $value ) || is_object( $value ) ) {
		return '';
	}

	$text = sanitize_text_field( (string) $value );
	if ( function_exists( 'mb_substr' ) ) {
		return mb_substr( $text, 0, $limit );
	}

	return substr( $text, 0, $limit );
}

/**
 * Build a privacy-safe rate-limit key.
 *
 * @return string
 */
function hea_lth_ops_lead_rate_key(): string {

	$remote_addr = isset( $_SERVER['REMOTE_ADDR'] )
		? sanitize_text_field( wp_unslash( (string) $_SERVER['REMOTE_ADDR'] ) )
		: 'unknown';

	return 'hea_lth_lead_rate_' . substr( wp_hash( $remote_addr ), 0, 32 );
}

/**
 * Check and increment lead intake rate limit.
 *
 * @return bool True when rate-limited.
 */
function hea_lth_ops_lead_rate_limited(): bool {

	$key   = hea_lth_ops_lead_rate_key();
	$count = (int) get_transient( $key );
	if ( $count >= 5 ) {
		return true;
	}

	set_transient( $key, $count + 1, HOUR_IN_SECONDS );
	return false;
}

/**
 * Handle a public, consented, non-diagnostic lead intake request.
 *
 * The first-contact form deliberately rejects medical narratives, files, and
 * diagnosis collection. Clinical details belong only in an appropriate
 * provider/clinic workflow, not in the public intake endpoint.
 *
 * @param WP_REST_Request $request REST request.
 * @return WP_REST_Response|WP_Error
 */
function hea_lth_ops_create_lead( WP_REST_Request $request ) {

	$honeypot = hea_lth_ops_request_text( $request, 'website', 120 );
	if ( '' !== $honeypot ) {
		return new WP_REST_Response(
			array(
				'status'  => 'ok',
				'message' => __( 'הפנייה התקבלה.', 'hea-lth-ops' ),
			),
			202
		);
	}

	if ( hea_lth_ops_lead_rate_limited() ) {
			return new WP_Error(
				'hea_lth_ops_rate_limited',
				__( 'נשלחו יותר מדי פניות בזמן קצר. נסו שוב מאוחר יותר.', 'hea-lth-ops' ),
				array( 'status' => 429 )
			);
	}

	$consent = rest_sanitize_boolean( $request->get_param( 'consent' ) );
	if ( ! $consent ) {
		return new WP_Error(
			'hea_lth_ops_consent_required',
			__( 'נדרשת הסכמה ליצירת קשר.', 'hea-lth-ops' ),
			array( 'status' => 400 )
		);
	}

	$allowed_services = hea_lth_ops_allowed_services();
	$service          = sanitize_key( hea_lth_ops_request_text( $request, 'service', 80 ) );
	if ( ! isset( $allowed_services[ $service ] ) ) {
		$service = 'general-private-health';
	}

	$name    = hea_lth_ops_request_text( $request, 'name', 120 );
	$contact = hea_lth_ops_request_text( $request, 'contact', 160 );

	if ( '' === $name || strlen( $contact ) < 6 ) {
		return new WP_Error(
			'hea_lth_ops_contact_required',
			__( 'נדרשים שם וטלפון או אימייל לחזרה.', 'hea-lth-ops' ),
			array( 'status' => 400 )
		);
	}

	$meta = array(
		'_hea_lth_service'      => $service,
		'_hea_lth_service_he'   => $allowed_services[ $service ],
		'_hea_lth_region'       => hea_lth_ops_request_text( $request, 'region', 120 ),
		'_hea_lth_timing'       => hea_lth_ops_request_text( $request, 'timing', 80 ),
		'_hea_lth_payer'        => hea_lth_ops_request_text( $request, 'payer', 80 ),
		'_hea_lth_name'         => $name,
		'_hea_lth_contact'      => $contact,
		'_hea_lth_source_url'   => esc_url_raw( hea_lth_ops_request_text( $request, 'source_url', 300 ) ),
		'_hea_lth_utm_source'   => hea_lth_ops_request_text( $request, 'utm_source', 120 ),
		'_hea_lth_utm_medium'   => hea_lth_ops_request_text( $request, 'utm_medium', 120 ),
		'_hea_lth_utm_campaign' => hea_lth_ops_request_text( $request, 'utm_campaign', 120 ),
		'_hea_lth_consent'      => '1',
		'_hea_lth_created_at'   => gmdate( 'c' ),
	);

	$post_id = wp_insert_post(
		array(
			'post_type'   => 'hea_lth_lead',
			'post_status' => 'private',
			'post_title'  => sprintf(
				/* translators: 1: service label, 2: lead name. */
				__( 'פנייה חדשה: %1$s — %2$s', 'hea-lth-ops' ),
				$allowed_services[ $service ],
				$name
			),
		),
		true
	);

	if ( is_wp_error( $post_id ) ) {
		return new WP_Error(
			'hea_lth_ops_lead_store_failed',
			__( 'לא הצלחנו לשמור את הפנייה. נסו שוב מאוחר יותר.', 'hea-lth-ops' ),
			array( 'status' => 500 )
		);
	}

	foreach ( $meta as $key => $value ) {
		update_post_meta( (int) $post_id, $key, $value );
	}

	$admin_email = sanitize_email( (string) get_option( 'admin_email' ) );
	if ( is_email( $admin_email ) ) {
		wp_mail(
			$admin_email,
			__( 'Hea-lth: פנייה חדשה מהאתר', 'hea-lth-ops' ),
			sprintf(
				"Service: %s\nRegion: %s\nTiming: %s\nPayer: %s\nName: %s\nContact: %s\nSource: %s\n\nNo medical details were collected in this first-contact form.",
				$allowed_services[ $service ],
				$meta['_hea_lth_region'],
				$meta['_hea_lth_timing'],
				$meta['_hea_lth_payer'],
				$name,
				$contact,
				$meta['_hea_lth_source_url']
			)
		);
	}

	return new WP_REST_Response(
		array(
			'status'  => 'ok',
			'lead_id' => (int) $post_id,
			'message' => __( 'קיבלנו את הפנייה. נחזור אליכם אחרי בדיקת התאמה ראשונית.', 'hea-lth-ops' ),
		),
		201
	);
}

/**
 * Return a deliberately small public health response.
 *
 * Do not expose filesystem paths, active plugins, credentials, or server details.
 */
function hea_lth_ops_healthcheck(): WP_REST_Response {
	$last_deployment = get_option( 'hea_lth_ops_last_deployment', array() );

	return new WP_REST_Response(
		array(
			'status'        => 'ok',
			'component'     => 'hea-lth-ops',
			'version'       => HEA_LTH_OPS_VERSION,
			'deployment_id' => is_array( $last_deployment ) ? (string) ( $last_deployment['deployment_id'] ?? '' ) : '',
		),
		200
	);
}

add_action(
	'rest_api_init',
	static function (): void {
		register_rest_route(
			'hea-lth-ops/v1',
			'/healthcheck',
			array(
				'methods'             => WP_REST_Server::READABLE,
				'permission_callback' => '__return_true',
				'callback'            => 'hea_lth_ops_healthcheck',
			)
		);
		register_rest_route(
			'hea-lth-ops/v1',
			'/leads',
			array(
				'methods'             => WP_REST_Server::CREATABLE,
				'permission_callback' => '__return_true',
				'callback'            => 'hea_lth_ops_create_lead',
			)
		);
	}
);
/**
 * Record successful package overwrites without storing credentials or request data.
 */
add_action(
	'upgrader_overwrote_package',
	static function ( string $package, array $data, string $package_type ): void {
		if ( 'plugin' !== $package_type || empty( $data['TextDomain'] ) || 'hea-lth-ops' !== $data['TextDomain'] ) {
			return;
		}

		hea_lth_ops_record_deployment();
	},
	10,
	3
);

/**
 * Optional Plugin Update Checker fallback.
 *
 * Direct GitHub Actions delivery is primary. Define HEA_LTH_OPS_MANIFEST_URL in
 * wp-config.php only when a separately governed distribution endpoint exists.
 */
add_action(
	'init',
	static function (): void {
		if ( ! defined( 'HEA_LTH_OPS_MANIFEST_URL' ) || ! is_string( HEA_LTH_OPS_MANIFEST_URL ) || '' === HEA_LTH_OPS_MANIFEST_URL ) {
			return;
		}

		$library = __DIR__ . '/lib/plugin-update-checker/plugin-update-checker.php';
		if ( ! is_readable( $library ) ) {
			return;
		}

		require_once $library;

		$factory = '\\YahnisElsts\\PluginUpdateChecker\\v5\\PucFactory';
		if ( ! class_exists( $factory ) ) {
			return;
		}

		try {
			$factory::buildUpdateChecker(
				esc_url_raw( HEA_LTH_OPS_MANIFEST_URL ),
				__FILE__,
				'hea-lth-ops'
			);
		} catch ( Throwable $error ) {
			// phpcs:ignore WordPress.PHP.DevelopmentFunctions.error_log_error_log -- Operational bootstrap faults must be visible without exposing credentials.
			error_log( 'Hea-lth Ops update checker failed to initialize: ' . $error->getMessage() );
		}
	},
	5
);
